### ISSUE TITLE
Problem after session complete 

### ISSUE THREAD

**Issue by DinoQuinten** [akaMrNagar/Mindful#100]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**

**Describe the bug**

**To Reproduce**

1. Start a focus session 
2. When the focus session ends and you try to start the focus session again it say you already have focus session running 
3. See error
4. Then you have to restart the application and it starts the session 

**Expected behavior**
It should either take you to the focus session of its running or it should just start a new session. 

**Screenshots**
![Screenshot_2024-10-07-22-11-32-16_985d972e5023e7d0b85a191419a75c8b](https://github.com/user-attachments/assets/3e0650b0-0868-473e-ad3e-55758511338d)

**Additional context**

**Log file**
You can get the log file from: _**Settings > Advance > Share crash logs**_

**Comment by akaMrNagar** [comment]
Buddy are you serious i mean it literally saying that you have active session so why do you clicking on start session instead you should click on 'view ' button 

![Screenshot 2024-10-07 231710](https://github.com/user-attachments/assets/725fdc92-d760-4cb3-934c-9e0dd555eb67)

**Comment by DeltriDev** [comment]
> Buddy are you serious i mean it literally saying that you have active session so why do you clicking on start session instead you should click on 'view ' button 
> 
> ![Screenshot 2024-10-07 231710](https://github.com/user-attachments/assets/725fdc92-d760-4cb3-934c-9e0dd555eb67)
> 

Hey, this actually happened to me too, I think you're not understanding the exact issue haha

Okay so when a session ends, even after I click on view and I get the congratulations screen, it still doesn't allow me to start a new session right away. After a bit I managed to do it, but yeah it's probably some kind of bug. I may get you a screen recording when I have some time

**Comment by akaMrNagar** [comment]
Sometimes the device takes time to kill the service which eventually leads to this issue but as far as i know it will not be more than 1,2 seconds if you think this is not the case then do let me know

**Comment by DeltriDev** [comment]
> Sometimes the device takes time to kill the service which eventually leads to this issue but as far as i know it will not be more than 1,2 seconds if you think this is not the case then do let me know

Sadly it's much more than 2 seconds. I put a focus session and hour ago and it ended exactly 30 minutes before the time I'm writing, and it still shows as "active" in app and doesn't allow me to start a new session. However, the blocked apps are unblocked and I can access them normally. I honestly don't know, I tried closing the so from the recents and removing the app by dragging from the top and nothing happens

**Comment by DeltriDev** [comment]
Perhaps this should be reopened?

**Comment by akaMrNagar** [comment]
I will need mote information about it to solve this as the sessions are working perfectly fine on my device also can you verify if the timer in notification has ended or not ?

**Comment by akaMrNagar** [comment]
To fix the issue temporarily consider refreshing the dashboard. It is just a minor bug (state not refreshing). I will fix it in the next update.
