### ISSUE TITLE
Additional Criteria for Limiting App Usage

### ISSUE THREAD

**Issue by thomasborgogno** [akaMrNagar/Mindful#101]
Currently, the app allows setting a daily time limit for other applications, which is quite helpful. However, it would be great to have additional criteria for limiting app usage. For example:

The ability to set limits based on **hourly usage**, not just daily. This would allow users to control app usage more granularly throughout the day.

A limit on the number of times an app can be opened per day, to reduce frequent but short usage sessions.

An option to enforce mandatory breaks, such as requiring a 30-minute break after every 5 minutes of usage.

Thanks for the beautiful app ❤️

**Comment by thomasborgogno** [comment]
Currently, the app allows setting a daily time limit for other applications, which is quite helpful. However, it would be great to have additional criteria for limiting app usage. For example:

The ability to set limits based on hourly usage, not just daily. This would allow users to control app usage more granularly throughout the day.

A limit on the number of times an app can be opened per day, to reduce frequent but short usage sessions.

An option to enforce mandatory breaks, such as requiring a 30-minute break after every 5 minutes of usage.

Thanks for the beautiful app ❤️

**Comment by akaMrNagar** [comment]
I am planning on adding more ways i will think about it too

**Comment by inusedname** [comment]
@akaMrNagar +1 it will be nice if we could have Session Timer (like you can use facebook for 5 minutes). Also we could implement a Time Restricting, which discourage you from modify the preset timer that you have set (espescially helpful for who continuosly add more time when the timer out)

**Comment by akaMrNagar** [comment]
> @akaMrNagar +1 it will be nice if we could have Session Timer (like you can use facebook for 5 minutes). Also we could implement a Time Restricting, which discourage you from modify the preset timer that you have set (espescially helpful for who continuosly add more time when the timer out)


Session based timer is coming and you can use INVINCIBLE mode on dashboard tab which does not allow user to modify timer when it runs out.

**Comment by inusedname** [comment]
![Screenshot_2024-10-29-12-00-19-905_com.burockgames.timeclocker.jpg](https://github.com/user-attachments/assets/b704a56d-25ef-43f8-87ce-33ee74516197)

I forgot the part to discourage user 😁 The challenge has done it job on making user stop browsing + they must type in case emergency use. Combination of session timer + challenge is amazing.
