### ISSUE TITLE
Different app block profiles

### ISSUE THREAD

**Issue by DeltriDev** [akaMrNagar/Mindful#104]
**Is your feature request related to a problem? Please describe.**
I would like the different focus profiles (study, programming etc) to also have different blocked apps.

**Describe the solution you'd like**
You'll choose your focus apps and if you switch from study focus to programming focus you'll be able to pick different apps to block

**Additional context**
Some apps may be distracting during studying, but needed when coding and vice versa

**Comment by akaMrNagar** [comment]
Seems like a good idea let me what i can do..

**Comment by akaMrNagar** [comment]
So basically, when you switch between different session types the app should remember what you have selected earlier ?

**Comment by DeltriDev** [comment]
> So basically, when you switch between different session types Mindful should remember what you have selected earlier ?

Exactly!

**Comment by akaMrNagar** [comment]
consider it done
