### ISSUE TITLE
Exclude apps from screen time (AoD Apps)

### ISSUE THREAD

**Issue by Large-M** [akaMrNagar/Mindful#107]
**Problem:**
Apps that are used as lock screens/always on displays are counted towards screen usage for the day.

**Solution:**
The ability to exclude select apps from screen usage through a toggle or similar feature.![Screenshot_20241112-224258.png](https://github.com/user-attachments/assets/45777e53-5484-45e3-81a2-4a6c9607ebe0)

**Comment by akaMrNagar** [comment]
Duplicate #89
