### ISSUE TITLE
Problem with count the time of mi clock app

### ISSUE THREAD

**Issue by Jum3an** [akaMrNagar/Mindful#11]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**

**Describe the bug**

The app count the clock from no where

I think that because of the wedget in the home screen but the phone was no screen on all this time and still say this those the pictures for more clear details and screenshot from another app which collect the right data

The phone is Redmi note 9 and the os is android 12 lastest official one from mi

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_2024-12-23-05-52-02-908_com.mindful.android.jpg](https://github.com/user-attachments/assets/ecd25d00-f355-41a5-9fe3-f464eb9c78b8)

![Screenshot_2024-12-23-05-52-26-847_com.burockgames.timeclocker.jpg](https://github.com/user-attachments/assets/17b5ae85-092b-45f5-8795-bd024d15d6a3)

**Additional context**

**Log file**
You can get the log file from: _**Settings > Advance > Share crash logs**_

**Comment by akaMrNagar** [comment]
By going to app info, you can exclude any app from the total usage stats.
