### ISSUE TITLE
Order and search App list

### ISSUE THREAD

**Issue by vinaooo** [akaMrNagar/Mindful#118]
**Describe the bug**
It's annoying to find an app in this list, it's not alphabetical and there is no search engine here

**To Reproduce**

Go to bedtime and try to add an app to 'Distracting apps' 

**Expected behavior**
A button to choose an way to order the app list, like alphabetical or most used maybe a search button to open a text box to write the app name 

**Screenshots**
![Screenshot_20241127-100039.png](https://github.com/user-attachments/assets/112b9011-9eae-4d99-a73a-12440e51f5a7)

**Comment by akaMrNagar** [comment]
Right now the apps are sorted on the basis of most used to least used for the current day. But been already thinking about adding a search bar along with some sorting options. But as you know Mindful is under heavy development so i thing it is going to take some time to implement this.
