### ISSUE TITLE
Why did you move the SourceCode to another Repo?

### ISSUE THREAD

**Issue by WreckingBANG** [akaMrNagar/Mindful#12]
Why did you move the SourceCode to Mindful-Private?

**Comment by akaMrNagar** [comment]
Thank you for letting me know, you are a savior. I forgot to make it private reason being there's too much going in my life😔. 

The reason behind moving the source code is that Mindful is already a mature app now, the only major feature remaining is Notification Batching which i am working on already. So being open source means anyone can just slap my code unethically to their app which i don't want.

**Comment by WreckingBANG** [comment]
Well, that is really bad and sad.

I also donated money to you because I was seeing a beautiful app that was exactly what I needed. Really disappointed that you removed the source code.

I understand that it can be annoying when people copy it, but making it closed-source is not a good solution.

I would really appreciate it if you could reconsider your decision.

Now I will sadly need to uninstall the app since I treat every closed-source app as untrusted, especially if it's registered as a device admin app.

It would also be fair to all the people who use the app to give them a notice that it is now closed source.

As I contributed translations. If you make it closed source, I want you to remove my translations. You licensed your code under GPL, so I have the right to request this.

**Comment by akaMrNagar** [comment]
I am really not sure but how can i protect it from unethical peoples. I really need some help deciding what will be best.


Beside this i have announced it through discussion and chagelog too.

**Comment by WreckingBANG** [comment]
You cannot really protect it. The only thing you can do is report the people that upload it illegal. I know you mentioned it in the discussions and the changlelog, but not everybody reads it after every release. Can you at least leave the old code on github and make all new updates closed source? 

If i knew that,  i would have never donated. I donated because i believed you are doing great work and i wanted to support that you made it open source. You can really not trust anyone anymore. Really disappointed.

At least send me the source code so that i can build the last open source release for myself. I really liked the app.

**Comment by akaMrNagar** [comment]
I am not milking it for money i could just upload the updated code it if you think i am not trust worthy (now which i think would be right choice). All of this is new to me

**Comment by akaMrNagar** [comment]
I think it is time to reconsider my silly action which i took without discussing with you all. Don't worry i will make it open again with the updated code and will continue to work here. Now that i know that Mindful matter to people more than any unethical entity. 

Which was the aim from the start

**Comment by WreckingBANG** [comment]
I know you are not wanting to make money. It would be super cool if you could upload the code again. That would make me, and a few other people really happy. It is not about that i dont trust you in particular. I just learned that you can trust nobody in this world anymore. This is why i only use open source stuff, so that i can verify it myself.

**Comment by akaMrNagar** [comment]
I am really sorry for my action which i can't undo but i will be more transparent about the issues in future don't worry i am not abandoning Mindful and all of you. I will reopen the code and updates just for the sake of trust that all of you have showed on me

**Comment by WreckingBANG** [comment]
Thank you so much.

**Comment by akaMrNagar** [comment]
I took that decision when i was low and going through some troubles in life, which turns out to be pile of mistakes.
Once again i would like to apologize for my silly actions

**Comment by WreckingBANG** [comment]
We are all human, we make mistakes. The important part is that you realized it was a mistake and that you are fixing it. 
Would be cool if you could write in this issue once the sourcecode is up again.

Thank you in advance.

**Comment by WreckingBANG** [comment]
Wow, thank you!!!! 
You really uploaded the source code again. 
Thank you so much!

**Comment by akaMrNagar** [comment]
I have nothing to hide. As always i request you to keep supporting me by helping me taking a right decision

**Comment by akaMrNagar** [comment]
All these cost us our 200 start on repo and some unhappy users (those who left us) 😔

**Comment by WreckingBANG** [comment]
If you need any help, just tag me. I am sadly not that experienced in Dart, so i cannot help with Code, but i will definitely finish the german translations soon so you can publish them!

**Comment by akaMrNagar** [comment]
Don't worry, I am capable enough but earlier i thought nobody cares about my work and time i put into the app so..
But thanks for asking.

**Comment by akaMrNagar** [comment]
https://github.com/akaMrNagar/Mindful/discussions/16
