### ISSUE TITLE
Active Period Not Working

### ISSUE THREAD

**Issue by Weldarvin** [akaMrNagar/Mindful#130]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**
N/A

**Describe the bug**
When active period is set for a restriction group or individual app, it still does not allow using the app in those periods. My understanding is that, I can use the app during that period regardless of any other limits. Correct? 

**To Reproduce**
1. Go to Statistics
2. Click on any app or select Restriction groups and create a group
3. Set Active Period to a time frame that includes your current time. 
4. Update/confirm and try opening restricted app

**Expected behavior**
App should open as normal without "Paused" overlay from mindful. 

**Screenshots**

**Additional context**
I tried this without any additional limits and still had the prompt that app is paused outside of active period even  though I set it so I am within the active period.

**Comment by akaMrNagar** [comment]
All the restrictions from the restriction groups and specific app are combined together.

whenever an app is launched the restriction in the associated group are verified then the specific app's restriction are verified, if any of the restriction is active then the pause dialog is shown.

Lets say you have a restriction group with active period set but also the app have timer then the pause dialog can be seen as the timer has ran out even if in active period.

**Comment by akaMrNagar** [comment]
I tried to recreate this and found that the active period is not updating correctly. I will fix this asap

**Comment by Weldarvin** [comment]
Thanks @akaMrNagar. I would await the fix.
I am enjoying the app so far and appreciate your time and attention to improving it.

**Comment by akaMrNagar** [comment]
Just found the bug, it was a silly mistake in calculating the remaining time from the active period end, lol😉

**Comment by Weldarvin** [comment]
Thanks for the quick resolution.
