### ISSUE TITLE
unsyncronised Focus Session timmer in notification and app 

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [akaMrNagar/Mindful#135]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**
yeah, first of all please fix this [Project Progress](https://github.com/users/akaMrNagar/projects/1) thing...... its just a non existing page 🤦 

now the bug.......

**Describe the bug**
When i started the Focus session....... and locked mmy device, after some time the Notification timer was showing the correct time where as the timer in the app was showing an incorrect time (probabily time stopped during screen locked)........ 

**To Reproduce**
Try to start an new session and lock the device.

**Expected behavior**
the timer should have continued and both the in app timer and the notification timer should have matched.

**Screenshots**
![Screenshot_20241211-100654](https://github.com/user-attachments/assets/46cc0f51-d182-434a-8d98-76d3ea15d991)
![Screenshot_20241211-100657](https://github.com/user-attachments/assets/bec1d518-fa60-4ecd-b749-3987c334ffb7)

**Additional context**
also even after the congratulations notification 
![Screenshot_20241211-102848](https://github.com/user-attachments/assets/8a0a07b8-a09d-4690-b3e3-34c0f851a82c)
the app kept showing that the focus session is still active 
![Screenshot_20241211-104223](https://github.com/user-attachments/assets/aff7aca5-8412-42a9-aa5b-7f85ba127dc8)

**Log file**
[Mindful-Logs-20241211-104551.json](https://github.com/user-attachments/files/18089923/Mindful-Logs-20241211-104551.json)

also, if you miss some mmmmmmmmm's or finding mmultiple in unnecesary, they are by there will 😆 (faulty kboard)

btw dhanyawad for the app......  really loving it

**Comment by akaMrNagar** [comment]
I am really sorry about the PROJECT PROGRESS, it is set to private but i have made it public. Thanks for letting me know as no one ever complained about it.

And for the synchronization it is minor bug and i will fix it asap but for now restarting the app will fix the issue.
