### ISSUE TITLE
Enable GitHub Discussions for Mindful Repo

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [akaMrNagar/Mindful#137]
Hey @akaMrNagar , have a look on [GH discussions](https://docs.github.com/en/discussions/quickstart) and make them available for the Mindful Repo...... As not everything we, users, wants to quote/say is not a bug or request....

See you there...... 🫡

**Comment by akaMrNagar** [comment]
Definitely 😜

**Comment by Bhardwaj10Ankit** [comment]
Hey @akaMrNagar also (obviously if you wish 😄 😉) whatever you plan for future but not starting to work on right away.... Please put that feature in polls of discussion..... So the users can vote them according to liking/usefulness...... Making it way easier for you to decide what to add in near future updates... 
🙏🏼

**Comment by akaMrNagar** [comment]
For now the planned features mainly includes notification scheduling and intuitive widgets
