### ISSUE TITLE
App Localization

### ISSUE THREAD

**Issue by MichelangeloDePascale02** [akaMrNagar/Mindful#61]
I understand that the application is still under heavy development, but I wanted to ask if it would be possible to contribute to it by localizing Mindful into other languages. Which system would be possible to use in this case?

**Comment by akaMrNagar** [comment]
To add localization support, we have to choose something that can handle strings on both flutter and android side. Adding localization to UI only is not that beneficial as the notification and dialogs too need to be localized.

**Comment by akaMrNagar** [comment]
I have started working on extracting text into arb file for English. We will use Crowdin for localization. Soon i will setup project on Crowdin as soon as i finish working on 'en' [English]

Till then will keep updating this task list:

- [ ]  Onboarding Screen
- [ ]  Permissions UI
- [ ]  Home/Dashboard 
- [ ]  Home/Statistics 
- [ ]  Home/Wellbeing
- [ ]  Home/Bedtime
- [ ]  Focus/Focus
- [ ]  Focus/Timeline
- [ ]  App Dashboard Screen 
- [ ]  Settings Screen

**Comment by akaMrNagar** [comment]
I have created project on Crowdin and uploaded both app_en.arb (flutter) and strings.xml(android) files.

The project is accessible at : https://crowdin.com/project/mindful

**Comment by akaMrNagar** [comment]
I am new to localization on Crowdin  so don't hesitate to let me know if you found any issue or suggestion

**Comment by WreckingBANG** [comment]
I can do all of the German Translations if you want.

**Comment by akaMrNagar** [comment]
hey @WreckingBANG  it will be cool
