### ISSUE TITLE
Bottom Navigation, AMOLED Theme, and Customizable Widgets (tiles)

### ISSUE THREAD

**Issue by Fennec7896** [akaMrNagar/Mindful#63]
Hello and thank you for this awesome app!

Bottom Navigation Menu
Moving the app's main navigation menu from the left side of the screen to the bottom would make it much easier to access with one hand, especially on larger devices. (Some text for me is being displayed wrong)

AMOLED Dark Theme:
Adding an AMOLED dark theme option would not only be aesthetically pleasing but also help conserve battery life on devices with AMOLED screens.

Customizable Dashboard
Let us remove the option to use a name. Also customizing the dashboard would be pretty nice. Some users might prioritize certain features over others, and having the flexibility to rearrange or select widgets (meaning the tiles) would improve usability.

**Comment by akaMrNagar** [comment]
What so you mean by "Some text for me is being displayed wrong" ? elaborate or better provide a screenshot.

Also all these feature are planned but right now i have lot in my plate. Soon these features will be introduced. Right now i am focusing on core features and localization so that localization contributors  can work parallelly with development.

**Comment by Fennec7896** [comment]
![Screenshot_2024-09-27-23-44-29-19_985d972e5023e7d0b85a191419a75c8b.jpg](https://github.com/user-attachments/assets/da3efa1b-3685-4445-9588-4ab5055ae336)

**Comment by akaMrNagar** [comment]
Ah, i see and thanks for the screenshot. I will add navigation feature in the next update keep an eye.

**Comment by Fennec7896** [comment]
Looking forward to it!

**Comment by akaMrNagar** [comment]
Added bottom navigation and AMOLED theme.

![Screenshot 2024-09-29 012821](https://github.com/user-attachments/assets/c542c1b4-a2e5-47c4-a057-794d9f0277de)

**Comment by Fennec7896** [comment]
Can you move about on the the settings menu?

**Comment by akaMrNagar** [comment]
Right now i am closing this issue. I know your request for Customizable Dashboard Tiles is not yet implemented but i have noted it down for future as i am planning to add more features on dashboard so implementing it right now is not in my priority so excuse me for this

**Comment by Fennec7896** [comment]
Can you move about on the the settings menu?

**Comment by akaMrNagar** [comment]
> Can you move "about" on the settings menu?

I have removed merged about and privacy tab in the new commit

**Comment by Fennec7896** [comment]
![Screenshot_2024-09-28-23-30-16-87_a5af3585a93e2016f6667aaf7e1e2f32.jpg](https://github.com/user-attachments/assets/6fb37d98-ea0a-4e05-99b4-7b7e24601a3f)

Hiding the labels as an option would be really cool too.

**Comment by akaMrNagar** [comment]
Maybe for future

**Comment by akaMrNagar** [comment]
but i think this is enough for now. i have to add more short content platforms.

**Comment by Fennec7896** [comment]
Alright looking pretty good!

**Comment by akaMrNagar** [comment]
Also i fixed the text overflow in the main initial navigation so you can use both

**Comment by akaMrNagar** [comment]
Fixed in #65
