### ISSUE TITLE
Backup statistics and settings

### ISSUE THREAD

**Issue by ymstnt** [akaMrNagar/Mindful#64]
Thanks for the app, it is really promising.

I have noticed there is currently no way to backup your statistics and settings. With proper backup/restore, a user could backup their statistics, data and settings and restore it later when needed, for example when switching to a new device.

Ideally a backup/restore could be customized to include statistics or settings only, or both of them.

Keep up the amazing work, so far the best wellbeing app I've ever seen.

**Comment by akaMrNagar** [comment]
That's a good suggestion but right now i am polishing and fixing bugs till then keep an eye on this issue
