### ISSUE TITLE
[Feature] Compatibility with custom clients

### ISSUE THREAD

**Issue by Yolomic** [akaMrNagar/Mindful#66]
**Is your feature request related to a problem? Please describe.**
Shorts blocking doesnt work on revanced youtube

**Describe the solution you'd like**
Apply short blocker on all *.*.android.youtube

**Additional context**

**Comment by akaMrNagar** [comment]
I initially thought about revanced but then i remember revanced already had a feature where you can completely turn off. Although i can add that

**Comment by akaMrNagar** [comment]
One more thing to implement this feature for other clients Mindful needs their package names. As mindful only subscribe to accessibility events from the specified packages. Which eventually result in better privacy and low performance overhead.

If i let it receive events from all  apps then it will drain more battery and also it is breach of trust.

**Comment by akaMrNagar** [comment]
So finally i added this feature without compromising performance and privacy. To block shorts on any youtube client the following conditions must be met:

1. The package name of the app must end with ".android.youtube"
2. The app must have set the open by default link to "www.youtube.com" just like the screenshot

![Screenshot 2024-09-29 160410](https://github.com/user-attachments/assets/2bf27edc-c4eb-43cc-9c58-c27214de37f3)


Now technical details about how Mindful will work - 

1. It will check if there exist an app which can open "www.youtube.com".
2. It will check if the app's package name ends with ".android.youtube"
3. Lastly it will only subscribe to those apps for accessibility events.

In this way it does not need to get events from all apps

**Comment by Yolomic** [comment]
Thats what i somewhat explained thanks ill await for next release love the app so far great job

**Comment by akaMrNagar** [comment]
Fixed in #67 
Now the user have to specifically make sure that the client has open by default enabled for "www.youtube.com"
