### ISSUE TITLE
Focus mode enhancements (like timing techniques, timers or stopwatch, amoled time display etc)

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [akaMrNagar/Mindful#70]
I would like to suggest having an option in focus mode where we can use it as a stopwatch and a timer with a pause option and with some enhanced focus timing tecnique (like pomodoro etc) options bundled, Also it'll be great if there's an option for amoled devices to keep the display op with the timer or stopwatch with pitch black background ( like [tranquilstopwatch](https://github.com/tibarj/tranquilstopwatch)) so the user can keep a track and stay motivated to not get distacted by unlocking the device unintentionally.

**Comment by akaMrNagar** [comment]
The AMOLED theme is coming to next update which is already live on GitHub and coming soon on Play Store.


The focus mode is inspired by SESSION app on mac along with addition to block distracting apps and DND. I don't understand the usage of just a stopwatch without any distractions blocking feature. 


Can you explain it's usage for the end user

**Comment by Bhardwaj10Ankit** [comment]
Stopwatch/timer as an addition to all that Mindful already provids...... 

It can be used in many ways as if someone is utilising the focus time for giving some sort of exam or reading session etc

**Comment by akaMrNagar** [comment]
I think you can already choose these types of sessions in session type on focus tab


Besides unlimited time focus sessions seems the feature to be considered. In this way user does not have to predifined time

**Comment by akaMrNagar** [comment]
AMOLED feature is already added and other requirement is similar to #105 which will be added asap.
