### ISSUE TITLE
Shorts timer to 0 instead of 5

### ISSUE THREAD

**Issue by Anish01234** [akaMrNagar/Mindful#74]
I kindly request the ability to set a time limit of zero for short sessions, rather than the current minimum of five minutes. Even a five-minute distraction can be detrimental to my productivity.

**Comment by akaMrNagar** [comment]
The minimum limit for timer is there only to respect INVINCIBLE MODE without this minimum time if ther user set the timer to 0 he cannot change the timer if he had INVINCIBLE MODE ON
