### ISSUE TITLE
Add pinned notification for screentime

### ISSUE THREAD

**Issue by Wh1teT1ger55** [akaMrNagar/Mindful#85]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**
Yes

**Is your feature request related to a problem? Please describe.**
It would be nice to have a notification which always shows todays screen time

**Describe the solution you'd like**
As described above

**Additional context**
No

**Comment by akaMrNagar** [comment]
If you haven't noticed Mindful have a home widget which lets you take a glance at your today's screen and data usage. Beside this to add an ongoing notification we have to run a service 24*7 which will drain user battery so i don't think this is necessary
