### ISSUE TITLE
Feature Request: Distraction Session Tracking

### ISSUE THREAD

**Issue by Claude-Kenni** [akaMrNagar/Mindful#86]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1)?**

* No, I haven't found anything related to distraction session tracking in the project progress.

**Is your feature request related to a problem? Please describe.**

* Yes, my feature request is related to the problem of lacking awareness of how much time is spent on distractions. Currently, Mindful offers focus sessions to track study or work time, but there's no way to track unproductive distractions.

**Describe the solution you'd like**

I propose a new feature called "Distraction Session." This feature would allow users to:

* Initiate a timed session specifically for distractions like social media browsing, watching videos, or checking games.
* Track the duration of the distraction session, helping users become more mindful of unproductive screen time.

**Additional context**

A distraction session feature would complement the existing focus session functionality in Mindful, providing a well-rounded approach to digital wellbeing. By tracking both focused work time and distracting activities, users can gain valuable insights into their digital habits and strive for better time management.

For transparency, I used Gemini to assist me in making this issue 🥹

**Comment by akaMrNagar** [comment]
I don't understand why you want to or start a session for distraction. As anyone uses sessions to track their progress they can easily find out how much time did they wasted by looking at the dashboard which includes total screen time and the focused time for today ?

**Comment by Claude-Kenni** [comment]
> I don't understand why you want to or start a session for distraction. As anyone uses sessions to track their progress they can easily find out how much time did they wasted by looking at the dashboard which includes total screen time and the focused time for today ?

I understand what you're trying to say, what I meant was that the smartphone is not the only thing I use but also laptop/pc thus, it doen't track my screen time on laptop. But you can ignore/reject this request if this doesn't align with the app's vision or some sort.  Anyways, thank you for your work and response, sir  :)

**Comment by akaMrNagar** [comment]
Thank you for understanding 😊
