### ISSUE TITLE
Exluding Apps from statistics

### ISSUE THREAD

**Issue by Wh1teT1ger55** [akaMrNagar/Mindful#89]
**Is your feature request related to a problem? Please describe.**
I have an App (AmpereFlow) installed which shows a screen overlay when the device is locked and charging.
Now the App shows 3h of screentime from AnpereFlow.

**Describe the solution you'd like**
Add the option to exclude certain apps from the screentime statistics.

**Comment by akaMrNagar** [comment]
What type of apps do you want to exclude ?

**Comment by brog-io** [comment]
My settings app, shows 8 hours haha

**Comment by akaMrNagar** [comment]
I believe this issue has been fixed in the latest 0.0.14 update can you update and recheck the timings. And do let me know about it

**Comment by Wh1teT1ger55** [comment]
> What type of apps do you want to exclude ?

In my case it's the [AmpereFlow](https://play.google.com/store/apps/details?id=com.androxus.batterymeter&amp;hl=de) App which uses the AOD function to display usefull battery info while charging the phone. In my case Mindful is detecting the AOD as foreground-usage

**Comment by akaMrNagar** [comment]
This make sense.
