### ISSUE TITLE
Timer difference between notification panel and in App 

### ISSUE THREAD

**Issue by knerd1** [akaMrNagar/Mindful#9]
![Screenshot_2024-12-16_15-33-04](https://github.com/user-attachments/assets/dfbc0694-ee01-4a6c-84c7-9a6df68faf7b)
![Screenshot_2024-12-16_15-33-12](https://github.com/user-attachments/assets/d44ea7f7-2e90-475b-bee1-98ce274e9d5a)
i can see the difference between in notification panel timer and in app timer. i think you have to fix this because many times its lead to misunderstanding.

**Comment by akaMrNagar** [comment]
As far as i know i have fixed this issue. Are you on the latest version?

**Comment by knerd1** [comment]
> As far as i know i have fixed this issue. Are you on the latest version?

i am on version 1.2.4 and last updated on 12 dec

**Comment by akaMrNagar** [comment]
I will take a look at it but does the timer in notification is slow or started late?

**Comment by akaMrNagar** [comment]
I have tried to recreate this bug but no luck. Is this happening every time you start a session or just once. One suggestion though try granting 'Ignore battery optimization' permission by going to Settings>Advance
