### ISSUE TITLE
Block website does not work when the URL bar is not on the top

### ISSUE THREAD

**Issue by DeltriDev** [akaMrNagar/Mindful#90]
**Describe the bug**
I use arc search, which has the URL bar on somewhere on the middle of the screen when typing and when your done it's completely hidden. That means that website block does not work at all!

**To Reproduce**

1. Go to Arc Search
2. Type the URL of a blocked site
3. Nothing happens

**Expected behavior**
The site should be blocked

**Screenshots**
![Screenshot_2024-10-06-08-25-05-84_41453ac94f418184dfd859d8c1bcdad8.jpg](https://github.com/user-attachments/assets/4b170189-6f9f-494a-be59-83e98a4e88e6)

**Comment by akaMrNagar** [comment]
I checked it out and it is a known issue with browsers not showing the url bar or full web address in the url bar. I don't know why these browsers keep hiding their url bar from user. Samsung Internet too have this problem.

I don't think that this is going to be fixed as Mindful can't  fetch the current opened website unless it is visible on the screen.  One more thing if you search then click on the url bar in arc Mindful works but Arc does not handle intents as it is supposed to be, It creates new tab for redirection which is not the indented behavior.

For more info see https://github.com/akaMrNagar/Mindful/issues/54#issuecomment-2369565926
