### ISSUE TITLE
Issues with browser

### ISSUE THREAD

**Issue by brog-io** [akaMrNagar/Mindful#91]
Is it possible this app crashes brave browser? I've been having issues with brave since I installed this app

**Comment by akaMrNagar** [comment]
It is not a crash but it redirects the user to safe search results. To prevent user from going back to unsafe result Mindful first back or pop out from the history stack then redirect the user to safe search results. 

So it is not a crash but it is more like reopen when user open the browser for the first time

**Comment by Alveel** [comment]
@akaMrNagar perhaps its an idea to make this more transparent to the user?
For example a popup after enabling the option in wellbeing, or creating a sub-option enabling/disabling the redirect?

The current behaviour came as a surprise to me and now I can't disable it, so a user might just uninstall at that point already or go through the effort to manually configure the safe search engine variant as default (perhaps adding a link to instructions to do this would be an idea?)

Thanks!
