### ISSUE TITLE
App Groups

### ISSUE THREAD

**Issue by WreckingBANG** [akaMrNagar/Mindful#95]
**Is your feature request related to a problem? Please describe.**
I want to group Apps together, like a Group for Entertainment Apps, so that i can limit the amount i spend with these Apps, but i can choose how much time i want to spend with the Group, not each App individually. For example: The Group Entertainment could contain a Youtube App and a Twitch App. I assign the Group 1 Hour. I can watch 1 Hour Youtube and no Twitch or 45 Minutes Twitch and 15 Minutes Youtube or any variation.

**Describe the solution you'd like**
Under Statistics > Most used Apps there could be a additional Tab with user created Groups. There you can assign the Times and what Apps are in which Group. Each App can only be in one Group.

**Additional context**
None

**Comment by akaMrNagar** [comment]
I am thinking about more ways to block apps instead of just timer so maybe i will consider this too but right now i can't tell

**Comment by DeltriDev** [comment]
It would also be cool to be able to see the usage for different categories, kinda like how it works on iOS

**Comment by WreckingBANG** [comment]
Thank you so much, exactly what i had in mind! 😍
