### ISSUE TITLE
[BUG] Unable to view statistics of previous weeks

### ISSUE THREAD

**Issue by W1zardK1ng** [akaMrNagar/Mindful#96]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**

**Describe the bug**
Unable to view statistics of previous weeks.

**To Reproduce**

1. Go to statistics tab
2. clicking the the arrow to view previous week does nothing.

**Expected behavior**
Should show stats of previous weeks.

**Comment by akaMrNagar** [comment]
This is not a bug Mindful only shows statistics for the current week only.
