### ISSUE TITLE
[Feature request] Option to manage tabs in navigation bar

### ISSUE THREAD

**Issue by W1zardK1ng** [akaMrNagar/Mindful#97]
Please add the option to rearrange and hide the tabs in the navigation bar.

Eg, i don't have any social media app in my phone, so i can hide the Wellbeing tab from the navigation bar.

**Comment by akaMrNagar** [comment]
I don't think this is necessary feature instead i can spend time on more important and priority tasks. If more people will ask about it then i will think about it.

Thank you for understanding
