### ISSUE TITLE
Focus mode seconds not padded

### ISSUE THREAD

**Issue by FortyGazelle700** [akaMrNagar/Mindful#98]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**
Yes

**Describe the bug**
The seconds in the countdown timer when using focus mode isn't padded

**To Reproduce**

1. Go to 'Mindful App'
2. Click on 'Focus Now'
3. Scroll down to 'Start and View Active Session'
4. Wait till seconds gets less than 10 (any minute will work)

**Expected behavior**

The screen should read 22:09

**Screenshots**

![Screenshot_20241006_162047_Mindful.jpg](https://github.com/user-attachments/assets/a67e7198-aec0-46e7-814e-cffd0a83881b)

![Screenshot_20241006_162147_GitHub.jpg](https://github.com/user-attachments/assets/f30c8a5a-117e-4e5d-811d-83ec856b69e1)

**Additional context**

It also occurs in the notifications

**Log file**
You can get the log file from: _**Settings > Advance > Share crash logs**_

N/A - Visual Bug

**Comment by akaMrNagar** [comment]
man are you serious ?
