### ISSUE TITLE
Add to F-droid

### ISSUE THREAD

**Issue by chrostino** [akaMrNagar/Mindful#99]
**Have you checked it on [Project Progress](https://github.com/users/akaMrNagar/projects/1) ?**
Yes

**Is your feature request related to a problem? Please describe.**
There are people with phones without google play and would like to not rely on it

**Describe the solution you'd like**
Making the app available on some f-droid repo, since it's FOSS it would have no problem to be published

**Additional context**
It could be published on the official repo, or one that is very popular like IzzyOnDroid or it's own dedicated one

**Comment by akaMrNagar** [comment]
Adding app to F-Droid is tedious and take too much time which i don't have right now . So i suggest downloading from GitHub.
Eventually i am going to do that but this is not the right time

**Comment by chrostino** [comment]
I understand, I didn't know it was such a tedious process, thanks for answering anyway
